services:
    # Blockchain
    blockchain-node:
        build: './smartcontracts'
        ports:
            - 8545:8545
        command: npx hardhat node

    # Server
    api-gateway:
        build: './server'
        image: server
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules/
            - /usr/src/app/dist/
        command:  npm run server:dev
        ports:
            - 3000:3000
    blocks-polling:
        build: './server'
        image: server
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules/
            - /usr/src/app/dist/
        command:  >
            sh -c "npm run bp:db:generate &&
                npm run bp:dev"
    blocks-consumer:
        build: './server'
        image: server
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules/
            - /usr/src/app/dist/
        command: >
            sh -c "npm run bc:db:generate &&
                npm run bc:dev"
    blocks-consumer-api:
        build: './server'
        image: server
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules/
            - /usr/src/app/dist/
        command: >
            sh -c "npm run bc:db:generate &&
                npm run bcapi:dev"
        ports:
            - 3012:3012
    metadata:
        build: './server'
        image: server
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules/
            - /usr/src/app/dist/
        command: >
            sh -c "npm run metadata:db:generate &&
                npm run metadata:dev"
        ports:
            - 3013:3013
    auth:
        build: './server'
        image: server
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules/
            - /usr/src/app/dist/
        command: npm run auth:dev
        ports:
            - 3011:3011

    # Server Dependencies
    database:
        image: 'postgres:latest'
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: root
    redis:
        image: redis
        ports:
            - 6379:6379
    rabbitmq:
        image: rabbitmq
        command: rabbitmq-server
        ports:
            - 5672:5672
            - 15672:15672

    # Client
    web:
        build: './web'
        image: web
        ports:
            - 5173:5173
        volumes:
            - ./web:/usr/src/app
            - /usr/src/app/node_modules/
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm run dev