services:
    blockchain-node:
        build: './smartcontracts'
        ports:
            - 8545:8545
        command: npx hardhat node
    server:
        build: './server'
        ports:
            - 3000:3000
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules/
        depends_on:
            - blockchain-node
        command: npm run start:dev
    web:
        build: './web'
        ports:
            - 5173:5173
        volumes:
            - ./web:/usr/src/app
            - /usr/src/app/node_modules/
        depends_on:
            - blockchain-node
            - server
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm run dev
