services:
    blockchain-node:
        build: './smartcontracts'
        ports:
            - 8545:8545
        command: npx hardhat node
    blocks-polling:
        build: './server'
        image: server
        ports:
            - 3000:3000
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules/
        depends_on:
            - blockchain-node
        command: npm run bp:dev
    web:
        build: './web'
        ports:
            - 5173:5173
        volumes:
            - ./web:/usr/src/app
            - /usr/src/app/node_modules/
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm run dev
    database:
        image: 'postgres:latest'
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: root
    redis:
        image: redis
        ports:
            - 6379:6379
    rabbitmq:
        image: rabbitmq
        command: rabbitmq-server
        ports:
            - 5672:5672
            - 15672:15672